INSERT INTO public.country VALUES ('AF', 'Afghanistan');
INSERT INTO public.country VALUES ('AX', 'Åland Islands');
INSERT INTO public.country VALUES ('AL', 'Albania');
INSERT INTO public.country VALUES ('DZ', 'Algeria');
INSERT INTO public.country VALUES ('AS', 'American Samoa');
INSERT INTO public.country VALUES ('AD', 'Andorra');
INSERT INTO public.country VALUES ('AO', 'Angola');
INSERT INTO public.country VALUES ('AI', 'Anguilla');
INSERT INTO public.country VALUES ('AQ', 'Antarctica');
INSERT INTO public.country VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO public.country VALUES ('AR', 'Argentina');
INSERT INTO public.country VALUES ('AM', 'Armenia');
INSERT INTO public.country VALUES ('AW', 'Aruba');
INSERT INTO public.country VALUES ('AC', 'Ascension Island');
INSERT INTO public.country VALUES ('AU', 'Australia');
INSERT INTO public.country VALUES ('AT', 'Austria');
INSERT INTO public.country VALUES ('AZ', 'Azerbaijan');
INSERT INTO public.country VALUES ('BS', 'Bahamas');
INSERT INTO public.country VALUES ('BH', 'Bahrain');
INSERT INTO public.country VALUES ('BD', 'Bangladesh');
INSERT INTO public.country VALUES ('BB', 'Barbados');
INSERT INTO public.country VALUES ('BY', 'Belarus');
INSERT INTO public.country VALUES ('BE', 'Belgium');
INSERT INTO public.country VALUES ('BZ', 'Belize');
INSERT INTO public.country VALUES ('BJ', 'Benin');
INSERT INTO public.country VALUES ('BM', 'Bermuda');
INSERT INTO public.country VALUES ('BT', 'Bhutan');
INSERT INTO public.country VALUES ('BO', 'Bolivia');
INSERT INTO public.country VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO public.country VALUES ('BW', 'Botswana');
INSERT INTO public.country VALUES ('BR', 'Brazil');
INSERT INTO public.country VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO public.country VALUES ('VG', 'British Virgin Islands');
INSERT INTO public.country VALUES ('BN', 'Brunei');
INSERT INTO public.country VALUES ('BG', 'Bulgaria');
INSERT INTO public.country VALUES ('BF', 'Burkina Faso');
INSERT INTO public.country VALUES ('BI', 'Burundi');
INSERT INTO public.country VALUES ('KH', 'Cambodia');
INSERT INTO public.country VALUES ('CM', 'Cameroon');
INSERT INTO public.country VALUES ('CA', 'Canada');
INSERT INTO public.country VALUES ('IC', 'Canary Islands');
INSERT INTO public.country VALUES ('CV', 'Cape Verde');
INSERT INTO public.country VALUES ('BQ', 'Caribbean Netherlands');
INSERT INTO public.country VALUES ('KY', 'Cayman Islands');
INSERT INTO public.country VALUES ('CF', 'Central African Republic');
INSERT INTO public.country VALUES ('EA', 'Ceuta and Melilla');
INSERT INTO public.country VALUES ('TD', 'Chad');
INSERT INTO public.country VALUES ('CL', 'Chile');
INSERT INTO public.country VALUES ('CN', 'China');
INSERT INTO public.country VALUES ('CX', 'Christmas Island');
INSERT INTO public.country VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO public.country VALUES ('CO', 'Colombia');
INSERT INTO public.country VALUES ('KM', 'Comoros');
INSERT INTO public.country VALUES ('CG', 'Congo - Brazzaville');
INSERT INTO public.country VALUES ('CD', 'Congo - Kinshasa');
INSERT INTO public.country VALUES ('CK', 'Cook Islands');
INSERT INTO public.country VALUES ('CR', 'Costa Rica');
INSERT INTO public.country VALUES ('CI', 'Côte d’Ivoire');
INSERT INTO public.country VALUES ('HR', 'Croatia');
INSERT INTO public.country VALUES ('CU', 'Cuba');
INSERT INTO public.country VALUES ('CW', 'Curaçao');
INSERT INTO public.country VALUES ('CY', 'Cyprus');
INSERT INTO public.country VALUES ('CZ', 'Czech Republic');
INSERT INTO public.country VALUES ('DK', 'Denmark');
INSERT INTO public.country VALUES ('DG', 'Diego Garcia');
INSERT INTO public.country VALUES ('DJ', 'Djibouti');
INSERT INTO public.country VALUES ('DM', 'Dominica');
INSERT INTO public.country VALUES ('DO', 'Dominican Republic');
INSERT INTO public.country VALUES ('EC', 'Ecuador');
INSERT INTO public.country VALUES ('EG', 'Egypt');
INSERT INTO public.country VALUES ('SV', 'El Salvador');
INSERT INTO public.country VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO public.country VALUES ('ER', 'Eritrea');
INSERT INTO public.country VALUES ('EE', 'Estonia');
INSERT INTO public.country VALUES ('ET', 'Ethiopia');
INSERT INTO public.country VALUES ('FK', 'Falkland Islands');
INSERT INTO public.country VALUES ('FO', 'Faroe Islands');
INSERT INTO public.country VALUES ('FJ', 'Fiji');
INSERT INTO public.country VALUES ('FI', 'Finland');
INSERT INTO public.country VALUES ('FR', 'France');
INSERT INTO public.country VALUES ('GF', 'French Guiana');
INSERT INTO public.country VALUES ('PF', 'French Polynesia');
INSERT INTO public.country VALUES ('TF', 'French Southern Territories');
INSERT INTO public.country VALUES ('GA', 'Gabon');
INSERT INTO public.country VALUES ('GM', 'Gambia');
INSERT INTO public.country VALUES ('GE', 'Georgia');
INSERT INTO public.country VALUES ('DE', 'Germany');
INSERT INTO public.country VALUES ('GH', 'Ghana');
INSERT INTO public.country VALUES ('GI', 'Gibraltar');
INSERT INTO public.country VALUES ('GR', 'Greece');
INSERT INTO public.country VALUES ('GL', 'Greenland');
INSERT INTO public.country VALUES ('GD', 'Grenada');
INSERT INTO public.country VALUES ('GP', 'Guadeloupe');
INSERT INTO public.country VALUES ('GU', 'Guam');
INSERT INTO public.country VALUES ('GT', 'Guatemala');
INSERT INTO public.country VALUES ('GG', 'Guernsey');
INSERT INTO public.country VALUES ('GN', 'Guinea');
INSERT INTO public.country VALUES ('GW', 'Guinea-Bissau');
INSERT INTO public.country VALUES ('GY', 'Guyana');
INSERT INTO public.country VALUES ('HT', 'Haiti');
INSERT INTO public.country VALUES ('HN', 'Honduras');
INSERT INTO public.country VALUES ('HK', 'Hong Kong SAR China');
INSERT INTO public.country VALUES ('HU', 'Hungary');
INSERT INTO public.country VALUES ('IS', 'Iceland');
INSERT INTO public.country VALUES ('IN', 'India');
INSERT INTO public.country VALUES ('ID', 'Indonesia');
INSERT INTO public.country VALUES ('IR', 'Iran');
INSERT INTO public.country VALUES ('IQ', 'Iraq');
INSERT INTO public.country VALUES ('IE', 'Ireland');
INSERT INTO public.country VALUES ('IM', 'Isle of Man');
INSERT INTO public.country VALUES ('IL', 'Israel');
INSERT INTO public.country VALUES ('IT', 'Italy');
INSERT INTO public.country VALUES ('JM', 'Jamaica');
INSERT INTO public.country VALUES ('JP', 'Japan');
INSERT INTO public.country VALUES ('JE', 'Jersey');
INSERT INTO public.country VALUES ('JO', 'Jordan');
INSERT INTO public.country VALUES ('KZ', 'Kazakhstan');
INSERT INTO public.country VALUES ('KE', 'Kenya');
INSERT INTO public.country VALUES ('KI', 'Kiribati');
INSERT INTO public.country VALUES ('XK', 'Kosovo');
INSERT INTO public.country VALUES ('KW', 'Kuwait');
INSERT INTO public.country VALUES ('KG', 'Kyrgyzstan');
INSERT INTO public.country VALUES ('LA', 'Laos');
INSERT INTO public.country VALUES ('LV', 'Latvia');
INSERT INTO public.country VALUES ('LB', 'Lebanon');
INSERT INTO public.country VALUES ('LS', 'Lesotho');
INSERT INTO public.country VALUES ('LR', 'Liberia');
INSERT INTO public.country VALUES ('LY', 'Libya');
INSERT INTO public.country VALUES ('LI', 'Liechtenstein');
INSERT INTO public.country VALUES ('LT', 'Lithuania');
INSERT INTO public.country VALUES ('LU', 'Luxembourg');
INSERT INTO public.country VALUES ('MO', 'Macau SAR China');
INSERT INTO public.country VALUES ('MK', 'Macedonia');
INSERT INTO public.country VALUES ('MG', 'Madagascar');
INSERT INTO public.country VALUES ('MW', 'Malawi');
INSERT INTO public.country VALUES ('MY', 'Malaysia');
INSERT INTO public.country VALUES ('MV', 'Maldives');
INSERT INTO public.country VALUES ('ML', 'Mali');
INSERT INTO public.country VALUES ('MT', 'Malta');
INSERT INTO public.country VALUES ('MH', 'Marshall Islands');
INSERT INTO public.country VALUES ('MQ', 'Martinique');
INSERT INTO public.country VALUES ('MR', 'Mauritania');
INSERT INTO public.country VALUES ('MU', 'Mauritius');
INSERT INTO public.country VALUES ('YT', 'Mayotte');
INSERT INTO public.country VALUES ('MX', 'Mexico');
INSERT INTO public.country VALUES ('FM', 'Micronesia');
INSERT INTO public.country VALUES ('MD', 'Moldova');
INSERT INTO public.country VALUES ('MC', 'Monaco');
INSERT INTO public.country VALUES ('MN', 'Mongolia');
INSERT INTO public.country VALUES ('ME', 'Montenegro');
INSERT INTO public.country VALUES ('MS', 'Montserrat');
INSERT INTO public.country VALUES ('MA', 'Morocco');
INSERT INTO public.country VALUES ('MZ', 'Mozambique');
INSERT INTO public.country VALUES ('MM', 'Myanmar (Burma)');
INSERT INTO public.country VALUES ('NA', 'Namibia');
INSERT INTO public.country VALUES ('NR', 'Nauru');
INSERT INTO public.country VALUES ('NP', 'Nepal');
INSERT INTO public.country VALUES ('NL', 'Netherlands');
INSERT INTO public.country VALUES ('NC', 'New Caledonia');
INSERT INTO public.country VALUES ('NZ', 'New Zealand');
INSERT INTO public.country VALUES ('NI', 'Nicaragua');
INSERT INTO public.country VALUES ('NE', 'Niger');
INSERT INTO public.country VALUES ('NG', 'Nigeria');
INSERT INTO public.country VALUES ('NU', 'Niue');
INSERT INTO public.country VALUES ('NF', 'Norfolk Island');
INSERT INTO public.country VALUES ('KP', 'North Korea');
INSERT INTO public.country VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO public.country VALUES ('NO', 'Norway');
INSERT INTO public.country VALUES ('OM', 'Oman');
INSERT INTO public.country VALUES ('PK', 'Pakistan');
INSERT INTO public.country VALUES ('PW', 'Palau');
INSERT INTO public.country VALUES ('PS', 'Palestinian Territories');
INSERT INTO public.country VALUES ('PA', 'Panama');
INSERT INTO public.country VALUES ('PG', 'Papua New Guinea');
INSERT INTO public.country VALUES ('PY', 'Paraguay');
INSERT INTO public.country VALUES ('PE', 'Peru');
INSERT INTO public.country VALUES ('PH', 'Philippines');
INSERT INTO public.country VALUES ('PN', 'Pitcairn Islands');
INSERT INTO public.country VALUES ('PL', 'Poland');
INSERT INTO public.country VALUES ('PT', 'Portugal');
INSERT INTO public.country VALUES ('PR', 'Puerto Rico');
INSERT INTO public.country VALUES ('QA', 'Qatar');
INSERT INTO public.country VALUES ('RE', 'Réunion');
INSERT INTO public.country VALUES ('RO', 'Romania');
INSERT INTO public.country VALUES ('RU', 'Russia');
INSERT INTO public.country VALUES ('RW', 'Rwanda');
INSERT INTO public.country VALUES ('BL', 'Saint Barthélemy');
INSERT INTO public.country VALUES ('SH', 'Saint Helena');
INSERT INTO public.country VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO public.country VALUES ('LC', 'Saint Lucia');
INSERT INTO public.country VALUES ('MF', 'Saint Martin');
INSERT INTO public.country VALUES ('PM', 'Saint Pierre and Miquelon');
INSERT INTO public.country VALUES ('WS', 'Samoa');
INSERT INTO public.country VALUES ('SM', 'San Marino');
INSERT INTO public.country VALUES ('ST', 'São Tomé and Príncipe');
INSERT INTO public.country VALUES ('SA', 'Saudi Arabia');
INSERT INTO public.country VALUES ('SN', 'Senegal');
INSERT INTO public.country VALUES ('RS', 'Serbia');
INSERT INTO public.country VALUES ('SC', 'Seychelles');
INSERT INTO public.country VALUES ('SL', 'Sierra Leone');
INSERT INTO public.country VALUES ('SG', 'Singapore');
INSERT INTO public.country VALUES ('SX', 'Sint Maarten');
INSERT INTO public.country VALUES ('SK', 'Slovakia');
INSERT INTO public.country VALUES ('SI', 'Slovenia');
INSERT INTO public.country VALUES ('SB', 'Solomon Islands');
INSERT INTO public.country VALUES ('SO', 'Somalia');
INSERT INTO public.country VALUES ('ZA', 'South Africa');
INSERT INTO public.country VALUES ('GS', 'South Georgia & South Sandwich Islands');
INSERT INTO public.country VALUES ('KR', 'South Korea');
INSERT INTO public.country VALUES ('SS', 'South Sudan');
INSERT INTO public.country VALUES ('ES', 'Spain');
INSERT INTO public.country VALUES ('LK', 'Sri Lanka');
INSERT INTO public.country VALUES ('VC', 'St. Vincent & Grenadines');
INSERT INTO public.country VALUES ('SD', 'Sudan');
INSERT INTO public.country VALUES ('SR', 'Suriname');
INSERT INTO public.country VALUES ('SJ', 'Svalbard and Jan Mayen');
INSERT INTO public.country VALUES ('SZ', 'Swaziland');
INSERT INTO public.country VALUES ('SE', 'Sweden');
INSERT INTO public.country VALUES ('CH', 'Switzerland');
INSERT INTO public.country VALUES ('SY', 'Syria');
INSERT INTO public.country VALUES ('TW', 'Taiwan');
INSERT INTO public.country VALUES ('TJ', 'Tajikistan');
INSERT INTO public.country VALUES ('TZ', 'Tanzania');
INSERT INTO public.country VALUES ('TH', 'Thailand');
INSERT INTO public.country VALUES ('TL', 'Timor-Leste');
INSERT INTO public.country VALUES ('TG', 'Togo');
INSERT INTO public.country VALUES ('TK', 'Tokelau');
INSERT INTO public.country VALUES ('TO', 'Tonga');
INSERT INTO public.country VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO public.country VALUES ('TA', 'Tristan da Cunha');
INSERT INTO public.country VALUES ('TN', 'Tunisia');
INSERT INTO public.country VALUES ('TR', 'Turkey');
INSERT INTO public.country VALUES ('TM', 'Turkmenistan');
INSERT INTO public.country VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO public.country VALUES ('TV', 'Tuvalu');
INSERT INTO public.country VALUES ('UM', 'U.S. Outlying Islands');
INSERT INTO public.country VALUES ('VI', 'U.S. Virgin Islands');
INSERT INTO public.country VALUES ('UG', 'Uganda');
INSERT INTO public.country VALUES ('UA', 'Ukraine');
INSERT INTO public.country VALUES ('AE', 'United Arab Emirates');
INSERT INTO public.country VALUES ('GB', 'United Kingdom');
INSERT INTO public.country VALUES ('US', 'United States');
INSERT INTO public.country VALUES ('UY', 'Uruguay');
INSERT INTO public.country VALUES ('UZ', 'Uzbekistan');
INSERT INTO public.country VALUES ('VU', 'Vanuatu');
INSERT INTO public.country VALUES ('VA', 'Vatican City');
INSERT INTO public.country VALUES ('VE', 'Venezuela');
INSERT INTO public.country VALUES ('VN', 'Vietnam');
INSERT INTO public.country VALUES ('WF', 'Wallis and Futuna');
INSERT INTO public.country VALUES ('EH', 'Western Sahara');
INSERT INTO public.country VALUES ('YE', 'Yemen');
INSERT INTO public.country VALUES ('ZM', 'Zambia');
INSERT INTO public.country VALUES ('ZW', 'Zimbabwe');